### ISSUE TITLE
oc.request element issue

### ISSUE THREAD

**Issue by pittss** [octobercms/ajax#11] opened 2022-06-30 12:33 UTC
Does not work
```
// Serialize an element with the request
oc.request('.some-element', 'onSomething', { data: someVar });
```
(error: Uncaught TypeError: element.matches is not a function)

Work
```
oc.request(document.querySelector('.some-element'), 'onSomething', { data: someVar });
```

OctoberCMS Version: 3.0.60

**Comment by samgeorges** [comment] 2022-06-30 23:24
This is likely caused by 4f531e89ed047fb714dc43f0ebe5f600729bcdaf

Will take a look, thanks

**Comment by samgeorges** [comment] 2022-06-30 23:38
Fixed by 20df7eeef09c2efd0e2f5d3293e51db7cb7c2a58

**Closed as completed by samgeorges** 2022-06-30 23:38 UTC
